// <auto-generated />
namespace FriendOrganizer.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addedMetting : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedMetting));
        
        string IMigrationMetadata.Id
        {
            get { return "202208111921057_addedMetting"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
